/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapUkDotxmlRouteImport } from './routes/sitemap-uk[.]xml'
import { Route as SitemapRuDotxmlRouteImport } from './routes/sitemap-ru[.]xml'
import { Route as SitemapItDotxmlRouteImport } from './routes/sitemap-it[.]xml'
import { Route as SitemapEsDotxmlRouteImport } from './routes/sitemap-es[.]xml'
import { Route as SitemapEnDotxmlRouteImport } from './routes/sitemap-en[.]xml'
import { Route as SitemapDeDotxmlRouteImport } from './routes/sitemap-de[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapUkDotxmlRoute = SitemapUkDotxmlRouteImport.update({
  id: '/sitemap-uk.xml',
  path: '/sitemap-uk.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRuDotxmlRoute = SitemapRuDotxmlRouteImport.update({
  id: '/sitemap-ru.xml',
  path: '/sitemap-ru.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapItDotxmlRoute = SitemapItDotxmlRouteImport.update({
  id: '/sitemap-it.xml',
  path: '/sitemap-it.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEsDotxmlRoute = SitemapEsDotxmlRouteImport.update({
  id: '/sitemap-es.xml',
  path: '/sitemap-es.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEnDotxmlRoute = SitemapEnDotxmlRouteImport.update({
  id: '/sitemap-en.xml',
  path: '/sitemap-en.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDeDotxmlRoute = SitemapDeDotxmlRouteImport.update({
  id: '/sitemap-de.xml',
  path: '/sitemap-de.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap-de.xml': typeof SitemapDeDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap-de.xml': typeof SitemapDeDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap-de.xml': typeof SitemapDeDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/portfolio'
    | '/services'
    | '/sitemap-de.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-uk.xml'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/portfolio'
    | '/services'
    | '/sitemap-de.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-uk.xml'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/portfolio'
    | '/services'
    | '/sitemap-de.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-uk.xml'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDeDotxmlRoute: typeof SitemapDeDotxmlRoute
  SitemapEnDotxmlRoute: typeof SitemapEnDotxmlRoute
  SitemapEsDotxmlRoute: typeof SitemapEsDotxmlRoute
  SitemapItDotxmlRoute: typeof SitemapItDotxmlRoute
  SitemapRuDotxmlRoute: typeof SitemapRuDotxmlRoute
  SitemapUkDotxmlRoute: typeof SitemapUkDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-uk.xml': {
      id: '/sitemap-uk.xml'
      path: '/sitemap-uk.xml'
      fullPath: '/sitemap-uk.xml'
      preLoaderRoute: typeof SitemapUkDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-ru.xml': {
      id: '/sitemap-ru.xml'
      path: '/sitemap-ru.xml'
      fullPath: '/sitemap-ru.xml'
      preLoaderRoute: typeof SitemapRuDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-it.xml': {
      id: '/sitemap-it.xml'
      path: '/sitemap-it.xml'
      fullPath: '/sitemap-it.xml'
      preLoaderRoute: typeof SitemapItDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-es.xml': {
      id: '/sitemap-es.xml'
      path: '/sitemap-es.xml'
      fullPath: '/sitemap-es.xml'
      preLoaderRoute: typeof SitemapEsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-en.xml': {
      id: '/sitemap-en.xml'
      path: '/sitemap-en.xml'
      fullPath: '/sitemap-en.xml'
      preLoaderRoute: typeof SitemapEnDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-de.xml': {
      id: '/sitemap-de.xml'
      path: '/sitemap-de.xml'
      fullPath: '/sitemap-de.xml'
      preLoaderRoute: typeof SitemapDeDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRoute,
  SitemapDeDotxmlRoute: SitemapDeDotxmlRoute,
  SitemapEnDotxmlRoute: SitemapEnDotxmlRoute,
  SitemapEsDotxmlRoute: SitemapEsDotxmlRoute,
  SitemapItDotxmlRoute: SitemapItDotxmlRoute,
  SitemapRuDotxmlRoute: SitemapRuDotxmlRoute,
  SitemapUkDotxmlRoute: SitemapUkDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
