/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapUkDotxmlRouteImport } from './routes/sitemap-uk[.]xml'
import { Route as SitemapRuDotxmlRouteImport } from './routes/sitemap-ru[.]xml'
import { Route as SitemapItDotxmlRouteImport } from './routes/sitemap-it[.]xml'
import { Route as SitemapEsDotxmlRouteImport } from './routes/sitemap-es[.]xml'
import { Route as SitemapEnDotxmlRouteImport } from './routes/sitemap-en[.]xml'
import { Route as SitemapDeDotxmlRouteImport } from './routes/sitemap-de[.]xml'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125ServicesRouteImport } from './routes/{-$lang}/services'
import { Route as Char123LangChar125PortfolioRouteImport } from './routes/{-$lang}/portfolio'
import { Route as Char123LangChar125PackagesRouteImport } from './routes/{-$lang}/packages'
import { Route as Char123LangChar125ExperienceRouteImport } from './routes/{-$lang}/experience'
import { Route as Char123LangChar125ContactRouteImport } from './routes/{-$lang}/contact'
import { Route as Char123LangChar125AboutRouteImport } from './routes/{-$lang}/about'
import { Route as Char123LangChar125PortfolioSlugRouteImport } from './routes/{-$lang}/portfolio_.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapUkDotxmlRoute = SitemapUkDotxmlRouteImport.update({
  id: '/sitemap-uk.xml',
  path: '/sitemap-uk.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRuDotxmlRoute = SitemapRuDotxmlRouteImport.update({
  id: '/sitemap-ru.xml',
  path: '/sitemap-ru.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapItDotxmlRoute = SitemapItDotxmlRouteImport.update({
  id: '/sitemap-it.xml',
  path: '/sitemap-it.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEsDotxmlRoute = SitemapEsDotxmlRouteImport.update({
  id: '/sitemap-es.xml',
  path: '/sitemap-es.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEnDotxmlRoute = SitemapEnDotxmlRouteImport.update({
  id: '/sitemap-en.xml',
  path: '/sitemap-en.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDeDotxmlRoute = SitemapDeDotxmlRouteImport.update({
  id: '/sitemap-de.xml',
  path: '/sitemap-de.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/{-$lang}/',
  path: '/{-$lang}/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125ServicesRoute =
  Char123LangChar125ServicesRouteImport.update({
    id: '/{-$lang}/services',
    path: '/{-$lang}/services',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125PortfolioRoute =
  Char123LangChar125PortfolioRouteImport.update({
    id: '/{-$lang}/portfolio',
    path: '/{-$lang}/portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125PackagesRoute =
  Char123LangChar125PackagesRouteImport.update({
    id: '/{-$lang}/packages',
    path: '/{-$lang}/packages',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125ExperienceRoute =
  Char123LangChar125ExperienceRouteImport.update({
    id: '/{-$lang}/experience',
    path: '/{-$lang}/experience',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125ContactRoute =
  Char123LangChar125ContactRouteImport.update({
    id: '/{-$lang}/contact',
    path: '/{-$lang}/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125AboutRoute = Char123LangChar125AboutRouteImport.update({
  id: '/{-$lang}/about',
  path: '/{-$lang}/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125PortfolioSlugRoute =
  Char123LangChar125PortfolioSlugRouteImport.update({
    id: '/{-$lang}/portfolio_/$slug',
    path: '/{-$lang}/portfolio/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/sitemap-de.xml': typeof SitemapDeDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/experience': typeof Char123LangChar125ExperienceRoute
  '/{-$lang}/packages': typeof Char123LangChar125PackagesRoute
  '/{-$lang}/portfolio': typeof Char123LangChar125PortfolioRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/portfolio/$slug': typeof Char123LangChar125PortfolioSlugRoute
}
export interface FileRoutesByTo {
  '/sitemap-de.xml': typeof SitemapDeDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/experience': typeof Char123LangChar125ExperienceRoute
  '/{-$lang}/packages': typeof Char123LangChar125PackagesRoute
  '/{-$lang}/portfolio': typeof Char123LangChar125PortfolioRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/portfolio/$slug': typeof Char123LangChar125PortfolioSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sitemap-de.xml': typeof SitemapDeDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/experience': typeof Char123LangChar125ExperienceRoute
  '/{-$lang}/packages': typeof Char123LangChar125PackagesRoute
  '/{-$lang}/portfolio': typeof Char123LangChar125PortfolioRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/portfolio_/$slug': typeof Char123LangChar125PortfolioSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sitemap-de.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-uk.xml'
    | '/sitemap.xml'
    | '/{-$lang}/about'
    | '/{-$lang}/contact'
    | '/{-$lang}/experience'
    | '/{-$lang}/packages'
    | '/{-$lang}/portfolio'
    | '/{-$lang}/services'
    | '/{-$lang}/'
    | '/{-$lang}/portfolio/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap-de.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-uk.xml'
    | '/sitemap.xml'
    | '/{-$lang}/about'
    | '/{-$lang}/contact'
    | '/{-$lang}/experience'
    | '/{-$lang}/packages'
    | '/{-$lang}/portfolio'
    | '/{-$lang}/services'
    | '/{-$lang}'
    | '/{-$lang}/portfolio/$slug'
  id:
    | '__root__'
    | '/sitemap-de.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-uk.xml'
    | '/sitemap.xml'
    | '/{-$lang}/about'
    | '/{-$lang}/contact'
    | '/{-$lang}/experience'
    | '/{-$lang}/packages'
    | '/{-$lang}/portfolio'
    | '/{-$lang}/services'
    | '/{-$lang}/'
    | '/{-$lang}/portfolio_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitemapDeDotxmlRoute: typeof SitemapDeDotxmlRoute
  SitemapEnDotxmlRoute: typeof SitemapEnDotxmlRoute
  SitemapEsDotxmlRoute: typeof SitemapEsDotxmlRoute
  SitemapItDotxmlRoute: typeof SitemapItDotxmlRoute
  SitemapRuDotxmlRoute: typeof SitemapRuDotxmlRoute
  SitemapUkDotxmlRoute: typeof SitemapUkDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LangChar125AboutRoute: typeof Char123LangChar125AboutRoute
  Char123LangChar125ContactRoute: typeof Char123LangChar125ContactRoute
  Char123LangChar125ExperienceRoute: typeof Char123LangChar125ExperienceRoute
  Char123LangChar125PackagesRoute: typeof Char123LangChar125PackagesRoute
  Char123LangChar125PortfolioRoute: typeof Char123LangChar125PortfolioRoute
  Char123LangChar125ServicesRoute: typeof Char123LangChar125ServicesRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125PortfolioSlugRoute: typeof Char123LangChar125PortfolioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-uk.xml': {
      id: '/sitemap-uk.xml'
      path: '/sitemap-uk.xml'
      fullPath: '/sitemap-uk.xml'
      preLoaderRoute: typeof SitemapUkDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-ru.xml': {
      id: '/sitemap-ru.xml'
      path: '/sitemap-ru.xml'
      fullPath: '/sitemap-ru.xml'
      preLoaderRoute: typeof SitemapRuDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-it.xml': {
      id: '/sitemap-it.xml'
      path: '/sitemap-it.xml'
      fullPath: '/sitemap-it.xml'
      preLoaderRoute: typeof SitemapItDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-es.xml': {
      id: '/sitemap-es.xml'
      path: '/sitemap-es.xml'
      fullPath: '/sitemap-es.xml'
      preLoaderRoute: typeof SitemapEsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-en.xml': {
      id: '/sitemap-en.xml'
      path: '/sitemap-en.xml'
      fullPath: '/sitemap-en.xml'
      preLoaderRoute: typeof SitemapEnDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-de.xml': {
      id: '/sitemap-de.xml'
      path: '/sitemap-de.xml'
      fullPath: '/sitemap-de.xml'
      preLoaderRoute: typeof SitemapDeDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/{-$lang}'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/services': {
      id: '/{-$lang}/services'
      path: '/{-$lang}/services'
      fullPath: '/{-$lang}/services'
      preLoaderRoute: typeof Char123LangChar125ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/portfolio': {
      id: '/{-$lang}/portfolio'
      path: '/{-$lang}/portfolio'
      fullPath: '/{-$lang}/portfolio'
      preLoaderRoute: typeof Char123LangChar125PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/packages': {
      id: '/{-$lang}/packages'
      path: '/{-$lang}/packages'
      fullPath: '/{-$lang}/packages'
      preLoaderRoute: typeof Char123LangChar125PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/experience': {
      id: '/{-$lang}/experience'
      path: '/{-$lang}/experience'
      fullPath: '/{-$lang}/experience'
      preLoaderRoute: typeof Char123LangChar125ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/contact': {
      id: '/{-$lang}/contact'
      path: '/{-$lang}/contact'
      fullPath: '/{-$lang}/contact'
      preLoaderRoute: typeof Char123LangChar125ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/about': {
      id: '/{-$lang}/about'
      path: '/{-$lang}/about'
      fullPath: '/{-$lang}/about'
      preLoaderRoute: typeof Char123LangChar125AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/portfolio_/$slug': {
      id: '/{-$lang}/portfolio_/$slug'
      path: '/{-$lang}/portfolio/$slug'
      fullPath: '/{-$lang}/portfolio/$slug'
      preLoaderRoute: typeof Char123LangChar125PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SitemapDeDotxmlRoute: SitemapDeDotxmlRoute,
  SitemapEnDotxmlRoute: SitemapEnDotxmlRoute,
  SitemapEsDotxmlRoute: SitemapEsDotxmlRoute,
  SitemapItDotxmlRoute: SitemapItDotxmlRoute,
  SitemapRuDotxmlRoute: SitemapRuDotxmlRoute,
  SitemapUkDotxmlRoute: SitemapUkDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LangChar125AboutRoute: Char123LangChar125AboutRoute,
  Char123LangChar125ContactRoute: Char123LangChar125ContactRoute,
  Char123LangChar125ExperienceRoute: Char123LangChar125ExperienceRoute,
  Char123LangChar125PackagesRoute: Char123LangChar125PackagesRoute,
  Char123LangChar125PortfolioRoute: Char123LangChar125PortfolioRoute,
  Char123LangChar125ServicesRoute: Char123LangChar125ServicesRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125PortfolioSlugRoute: Char123LangChar125PortfolioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
